CMamba_v1: 'CryptoMamba/v1.yaml'
CMamba_v2: 'CryptoMamba/v2.yaml'
LSTM_bi_nv: 'LSTM/lstm_bi_nv.yaml'
LSTM_bi_v: 'LSTM/lstm_bi_v.yaml'
LSTM_nv: 'LSTM/lstm_nv.yaml'
LSTM_v: 'LSTM/lstm_v.yaml'
GRU_nv: 'GRU/gru_nv.yaml'
GRU_v: 'GRU/gru_v.yaml'
SMamba_nv: 'SMamba/smamba_nv.yaml'
SMamba_v: 'SMamba/smamba_v.yaml'
iTransformer_v: 'iTransformer/itransformer_v.yaml'
iTransformer_nv: 'iTransformer/itransformer_nv.yaml'
CMambaT_w14: 'CryptoMamba/t1.yaml'
CMambaT_w60: 'CryptoMamba/t2.yaml'
CMambaT_w60f8: 'CryptoMamba/t3.yaml'
CMambaT_w60f6: 'CryptoMamba/t4.yaml'
CMambaT_w60f11: 'CryptoMamba/t5.yaml'
CMambaT_w60f12: 'CryptoMamba/t6.yaml'
CMambaT_w60_revin: 'CryptoMamba/t7.yaml'
CMambaT_w60_revin_a05: 'CryptoMamba/t8.yaml'
CMambaT_w60f8_revin: 'CryptoMamba/t9.yaml'
CMambaT_w60_dist: 'CryptoMamba/t10.yaml'
CMambaT_w60f8_dist: 'CryptoMamba/t11.yaml'
CMambaT_w60_mix: 'CryptoMamba/t12.yaml'
CMambaT_w60_mix_bi: 'CryptoMamba/t13.yaml'
